name: clipseg-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - scipy
  - matplotlib-base
  - pip
  - pip:
    - torch
    - torchvision
    - opencv-python
    - git+https://github.com/openai/CLIP.git
